---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dev-app
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: ecitanand/http:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-port-app
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - nodePort: 30000
      port: 8080
      targetPort: 80
